-- this maps to an actionlist / storedlist in the application
-- code. the action list is the configuration and blocking
-- component where all the data for the list is kept in the
-- database
create table list (
    id bigint generated by default as identity,
    -- which action (block, warn, allow) will be performed
    action tinyint check (action between 0 and 4),
    -- the configuration id associated with the last time the list
    -- was loaded
    last_configuration_id char varying,
    -- the name of the list
    name char varying,
    -- the type (flat-file, regex, etc)
    type tinyint check (type between 0 and 2),
    primary key (id)
);

-- the source (a local or remote file) for parsing into
-- lines in the database
create table source (
    id bigint generated by default as identity,
    -- the location of the source (http:// or /path)
    uri character varying not null,
    -- the latest loaded version of the source
    version bigint not null default 0,
    -- if compression is used on disk then this specifies what type
    compression character varying,
    -- if this time is exceeded potentially download again (if no etag available)
    cache_until timestamp(2) with time zone,
    -- where it is cached on disk
    cache_path character varying,
    -- the etag provided by the server to identify the resource content
    etag character varying,
    -- the on disk hash
    hash character varying,
    -- the hash of the contents (if compression is in use)
    content_hash character varying,
    primary key (uri)
);

-- a single parsed line from a source
create table line (
    -- the list the line is from
    list_id bigint not null,
    -- the source the line is from
    source_id bigint not null,
    -- the hostname (this should be the query name match)
    hostname char varying not null,
    -- what the hostname should resolve to (usually 0.0.0.0 which is a block)
    resolve_to char varying(39),
    -- the version of the source if it has been loaded multiple times
    source_version bigint not null default 1,
    primary key (list_id,source_id,hostname,resolve_to, source_version)
);

-- when searching by list id and source id this is useful
CREATE INDEX line_list_source ON line(list_id, source_id);
-- ths index facilitates searching for block items during the block process
CREATE INDEX line_list_source_hostname_version ON line(list_id, source_id, hostname, source_version)